apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apollo-router
spec:
  ingressClassName: apollo-router
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apollo-router
            port:
              number: 80